CLUSTAL multiple sequence alignment by MUSCLE (3.8)


CAI34369.1      MFILYYSLLNNNMIKI----KFENLLVSIVVSVVIFFNTISTTMLDRTFFQAKANY---L
CAI33309.1      -------MSNMSSIKV----SIYQLLFYVSFIIIVGSKYLRETVFVNAYPLLSELIKVLI
CAI33441.1      MLVKVKGGFKVSLSRVKTDVKLNEFLFGLAFYPWLIAWLFTSTFYKDFIHPY-GIIKTWE
CAI34080.1      --------MKIVIQRR----SLPEILALSALTIFLVMSIFDVTFYVQYLPK--IVHRILI
CAI34348.1      -------MMKVVIKRK----SLPEILALSALTIFLVVSILDVTFYVQYLPK--VVYKILI
CAI34657.1      -------MMKVVIKRK----SLPEILALSALTIFLVVSILNVTFYVQYLPK--VVYKILI
CAI34310.1      --------MKITIKRY----SLPEILGLAALAIFLLFSLLDVSFYVQYISP--MLYKAAI
CAI34286.1      --------MKITIKRY----SLPEILGLAALAIFLLFSLLSITLYAQYISI--KVYFIAL
CAI34328.1      --------MKITIKRY----SLPEILGLAALAIFLLFSLLSITLYAQYISI--KVYFIAL
CAI34519.1      --------MKITIKRY----SLPEILGLAALAIFLLFSLLSITLYAQYISI--KVYFIAL
                         :    .     .: ::*    .   :    :  :.                

CAI34369.1      LLVVLLLGLRFMFPTRISFKYLIFSSLLLLSGILVYFQTGKLNFLVYSALLVL-LVNVDM
CAI33309.1      IIACIFLLLK-YILEPHTKKFIIFSIVILTIGVVVSYNSDSFFILMPVVALILNMSNIDI
CAI33441.1      YVGLFFLLFK-FMLGKSKIKSIIITPIILLIGFIVSYDNGNASFVAYTLTLIYSSRDINF
CAI34080.1      AILLILLVIKESYKRKLDYRTIISLFSTVLIYLLIGKMSTFSSNIAIGFIFIYVLRDIPF
CAI34348.1      AISLILLVIKELYKRKFDYRTIISLFATVLMYLLIGRVSTLNSNIAIGIIFIYALRDIPF
CAI34657.1      AISLILLVIKELYKRKFDYRTIISLFATVLMYLLIGRVSTLNSNIAIGIIFIYALRDIPF
CAI34310.1      FLIIMLIILKEFVSGSNSFESLLGLLGVSTLYFIIGSVTSYTSFIVLGLSLIYSLRDIPF
CAI34286.1      FGIILLIFLKELISESYNLKSVIGLFVIFTLCFIIGTVTNYAYFFILGLFLIYSLRNLPF
CAI34328.1      FGIILLIFLKELISESYNLKSVIGLFVIFTLCFIIGTVTNYAYFFILGLFLIYSLRNLPF
CAI34519.1      FGIILLIFLKELISESYNLKSVIGLFVIFTLCFIIGTVTNYAYFFILGLFLIYSLRNLPF
                    ::: :.           ::         .::   .     .     ::    :: :

CAI34369.1      KVVLKTYLIVAGILVLSVFLLSLLGAVPNLQYNR-EG---VIRNSFGFIYPTDFASHCFY
CAI33309.1      TKVIKVWLIEIIALMIFLAICYRLNIVGEVINSA-IRSDGKIRYALGYKYSTFSSNYFFH
CAI33441.1      RNLVRNTMFCQIGVVGTVIVSSLLGIIPNELALTYSEGVIRSRYGLGFHYTSFTPNYFLS
CAI34080.1      KSVAKISLAVSVFMLLFVIASAKLGVIINYLEIS-GP---RVRSYLGFRYALYPSILLMN
CAI34348.1      KSVAKTSLAVSVLILLFVITSAKLGVIINYLEIS-GT---RVRSYLGFRYALFPSILMMN
CAI34657.1      KSVAKTSLAVSVLILLFVITGAKLGVIINYLEIS-GT---RVRSYLGFRYALFPSILMMN
CAI34310.1      SKVVKVAFIISVAMLFLVILSSKIGFIPDYIEFS-ST---RVRHYLGFRYSLFPSTIMMN
CAI34286.1      SDVAKVSFIISISVLLLVVLSSKLGIIPDYVEIW-PT---RVRHYLGFRYSLLPSTLMMN
CAI34328.1      SDVAKVSFIISISVLLLVVLSSKLGIIPDYIEIS-PT---RVRHYLGFRYSLLPSTLMMN
CAI34519.1      SDVAKVSFIISISVLLLVVLSSKLGIIPDYIEIS-PT---RVRHYLGFRYSLLPSTLMMN
                  : .  :     ::  :     :. : :             *  :*: *.   .   : 

CAI34369.1      LFLAFSYLLKDKFIWI---RSLIGVLLSFFIIKYCDARLNALSIILATIIFIFFYFNEDK
CAI33309.1      VTIFYLYLRKHMIKYV---EIITLFLINLYLYALTDTRAVFYYSTAAIVICLLLKMFK--
CAI33441.1      ILLEYVYLKGEK--YWTIKELFICVLLNIVIYKYTDTRLTFIMVFILLLISFSRRFVS--
CAI34080.1      VIAITLYLKQNNIRYW---QWLLLTLSVYWVYGQTDSRLTFYNSCILLVFNILIKWFPD-
CAI34348.1      IVAIVFYLKQNKIQYW---QWLLLSLSAYWLYDETDSRLTFYSSCILLICSLLIRWIPE-
CAI34657.1      IVAIVFYLKQNKIQYW---QWLLLSLSAYWLYDETDSRLTFYSSCILLICSLLIRWIPE-
CAI34310.1      IIAISFFLKQETVSYQ---RLFILFLVSMYLYLETDSRLTFISSSLLLLANLAMKLIPT-
CAI34286.1      IIAISFFLKQENASYP---RLLVLFLLSGWLYVETDSRLTFINSCLFLLVNLIMKLSPS-
CAI34328.1      IIAISFFLKQENASYP---RLLVLFLLSGWLYVETDSRLTFINSCLFLLVNLIMKLSPS-
CAI34519.1      IIAISFFLKQENASYP---RLLVLFLLSGWLYVETDSRLTFINSCLFLLVNLIMKLSPS-
                :     :*      :      :   *    :    *:*          :  :        

CAI34369.1      KFRIYSISPYSVVLCSSIMMYLSYIFSWG---------SPFLVSINKLITGRLALGKNAF
CAI33309.1      -IKTYSIILNKYSMLF--SAIIAGVLSWSY-----RYRLPFFDQLDLILTGRLRLGSAAF
CAI33441.1      INMNFKFLKYLLTLIYPIMAYMTYWLTAKF-----DSRNSLLSLINNLLSQRLRFGQEGL
CAI34080.1      ILSKLGNVFKIFRLTFIINAIISFWISINYLGSNNSFVNSFLFKLNHMLGGRLFLANKSL
CAI34348.1      LFSKFGYIFKAFKLTFIINAVVSFWVSFTYLNLSHSYINNLFLKLDYILGGRIYLMNKSL
CAI34657.1      LFSKFGYIFKAFKLTFIINAVVSFWVSFTYLNLSHSYINNLFLKLDYILGGRIYLVNKSL
CAI34310.1      VIEKFSLLLKFFTLTYFVNAYLSYWISKNYLRTSNALLNHFFHQADQFLGGRIYLSNRSL
CAI34286.1      IIEKVGRLLKLFSFTYFINACLSYWIAKTYLNTSNVVLNQFFYQVDQFLGGRIYYSNRSL
CAI34328.1      IIEKVGRLLKLFSFTYFINACLSYWIAKTYLNTSNVVLNQFFYQADQFLGGRIYYSNRSL
CAI34519.1      IIEKVGRLLKLFSFTYFINACLSYWIAKTYLNTSNVVLNQFFYQADQFLGGRIYYSNRSL
                             :       ::  .:             ::   : ::  *:   . .:

CAI34369.1      NTFDVHLFGTRDVLFKGSGGKTEAVID---YNYVDSSYVQMLFTYGVIPLVLLICMYVVI
CAI33309.1      NNFHITFFG-QKIRWIYE----QNMFSELIYNYVDSSYLNILFGFGIIILLLILVGYYII
CAI33441.1      RRYPLRLFG-THIQWDA---------SANSYLYVDSSYINILISYGTIIFFLTLISYSII
CAI34080.1      ELFGFGLFG-KQVDWNGNGLTIEGVRNYQTYLYVDNLYIQILQKFGLLVLVLMLALLTLT
CAI34348.1      NLYGFGLFG-RPVEWNGNGLTIEGVRNYQTYLYVDNLYVQILQKFGLLALGIMLLVLTLT
CAI34657.1      NLYGFGLFG-RPVEWNGNGLTIEGVRNYQTYLYVDNLYVQILQKFGLLALGIMLLVLTLT
CAI34310.1      SLYGYGILG-QKIAWVGNALNAQGERSTDAYLYVDNLYIQILQHFGLIALIIILSLLTAT
CAI34286.1      SLYGYKLLG-QKIDWIGNGLSIQGERSTETYLYVDNLYIQILQHFGLIVSVIILSLLTIT
CAI34328.1      SLYGYKLLG-QKIDWIGNGLSIQGERSTETYLYVDNLYIQILQHFGLIVSVIILSLLTIT
CAI34519.1      SLYGYKLLG-QKIDWIGNGLSIQGERSTETYLYVDNLYIQILQHFGLIVSVIILSLLTIT
                  :   ::*   : :           .   * ***. *:::*  :* :   : :      

CAI34369.1      SREQYKQGQYLYVVILSLVALNCMIEAFWFVPTYNIFMFLL----FTKNTFLNKSLNNFN
CAI33309.1      GEKKLSRDTY-YTMMIVFLSLHSTFDPQLIDIVYNPAILFLGYVIYNEDEIKNLNKIY--
CAI33441.1      MKKVIINQNKTLLIVLIFWSVRACIDPQLFLLWFNPFLFLIAR------TFLDEREEIGD
CAI34080.1      LFKAIKKDQWVIAFILIVMSFQSMIDDLNMYLHYNIFWILIGSLIYTQYHYSNEGT----
CAI34348.1      LFKVIKRREWVLSFILILMSFHSMIDDLNLYLHYNIFWILLGSLIYPDYQFSDESDEELG
CAI34657.1      LFKVIKRREWVLSFILILMSFHSMIDDLNLYLHYNIFWILLGSLIYPDYQFSDESDEELG
CAI34310.1      LVKLLRKGQIVLSIIIVSLSFHALIDDLILSIHYNIFWILLGSLIYSNYQFSEERYGEVE
CAI34286.1      LVKLLKKGQMVLGIILVILSFHALIDDLILNLYYNIFWVLIGMLIYKKYQFYDKKQLTIE
CAI34328.1      LVKLLKKGQMVLGIILVILSFHALIDDLILNLYYNIFWVLIGMLIYKKYQFYDKKQLTIE
CAI34519.1      LVKLLKKGQMVLGIILVILSFHALIDDLILNLYYNIFWVLIGMLIYKKYQFYDKKQLTIE
                  :   .      .::   :... ::   :   :*   .::           :       

CAI34369.1      PLDKTELLN---
CAI33309.1      ------------
CAI33441.1      DITYMCIE----
CAI34080.1      ------------
CAI34348.1      ENSFEEII----
CAI34657.1      ENSFEEII----
CAI34310.1      NDSLRRTVREGY
CAI34286.1      ------------
CAI34328.1      ------------
CAI34519.1      ------------
                            
