CLUSTAL multiple sequence alignment by MUSCLE (3.8)


AAT85653.1          ----MIYLLFFFALFMICTFLTHRRQA-----LYVVS-ALVFLFLALTYPS--GGDWIGY
ABI98976.1          ----MEYMLLCFWLAISCCSVKVS--------LSKINILLIFIFLSGAYSW--GYDWIRY
WP_046788607.1      ----MEYMLLCFWLAISCCSVKVS--------LSKINILLIFIFLSGAYSW--GYDWIRY
WP_000456161.1      ----MEYMLLCFWLAISCCSVKVS--------LSKINILLIFIFLSGAYSW--GYDWIRY
BAQ00746.1          ----MLIYNTIFVFLSFLALLDLSHKKNLLFFLFPCFILLLLTAIRGNG----GDDFYVY
AAM27879            ----MAYLFYC-FLTLPFALFSVFLRRDFQFLLFLFFVAICVFVFGFSYKV--GSDWYNY
BAQ01563.1          -----MYWIYCLFLLFIVSLLNKG---RYSTLAYKASLLIIFIFATGNYYN--GVDWINY
ACA24852.1          MTVSIYLLLLAFVFLLAMSDFFIIADARNRFLLYIILFSLLVTFIGLRYQT--GLDWLFY
ACA24840.1          MTVSIYLLFLAFVFLLAMSDFFIIADARNRFLLYIILFSLLVTFIGLRYQT--GLDWLFY
AHB32861.1          ----MAFYYTV-WFLISIFSMFSS-PKPEAKVLYIVFLAFLCLMTGLRYEV--GGDWENY
AHB32215.1          ----MNIYILI-WFFIVAINFISNYKTYINKIFFLLFFLFLFIFIGLRFKV--GGDWDNY
AHB32799.1          ----MYLYFFI-WIYIIVANFLSNYKTSLSKLFFIFTIVFLIFFIGLRFQI--GGDWYSY
BAQ01293.1          ----MAIYIFI---SISCLISYVLSNNDKNSLSPRFLLIILTLFTGLSYTN--GWDWYGY
AQU71788.1          ----MEFYYLILLFLVIVSIISAGFDKKTHFNLFLAFTICVFFITISSMRWERGTDWVSY
                                                                         * *:  *

AAT85653.1          FLHYDCMVNEQCNNGFI--MFEPGYELIVSLFG-YLGFQTIIIFIAAVNVILILN---FA
ABI98976.1          REYYENVF---LISDLVTWIYEPGFTFILFVNK-LLNL-DYHWVVVTCTLILSVNVYKYI
WP_046788607.1      REYYENVF---LISDLVTWIYEPGFTFILFVNK-LLNL-DYHWVVVTCTLILSVNVYKYI
WP_000456161.1      REYYENVF---LISDLVTWIYEPGFTFILFVNK-LLNL-DYHWVVVTCTLILSVNVYKYI
BAQ00746.1          EKYFNA-----LPNEIF--NYGYGYYSLNMFVK---NFGEYPFFIIISSIICITLQAIFI
AAM27879            FSYFDS--------GCTGFEFDVGFEYLCSGFN-WLGI-GYWFFSFSIKAFYIVTLAWFL
BAQ01563.1          QKHYEFISNSGISSEYF--AYEPGFLLLMYIFGNVLDIKNFHVIVIFISSISILSLSKFI
ACA24852.1          NNLFNG--------EGFSLAIEPGYYFFSYVSSFLMGY--WIYQALITAVLIICLKTFFE
ACA24840.1          NNLFNG--------EGFSLAIEPGYYFFSYVSSFLMGY--WIYQALITAVLIICLKTFFE
AHB32861.1          LNIYDYFKGVNIIEALT--ITEPAYGLLNYIGQ-LLDFKTIIFVNAICSIFFYSFFYKFS
AHB32215.1          LILYENFKYLNFKEALF--FFEPGYSLLNILGN-FLQIKDIWFVNLCSSALVCFFLFITF
AHB32799.1          QLIYEMFIGEKFKDAIH--IAEPGYSLLNILGL-HFGFADTLFVNLMSAVIIGCFLYLSF
BAQ01293.1          LDFYNNIQNEGVSAIYEYNIYGIEYLYLIYLYIVGLSGGSFSLFILLNAIIINFLIYSFC
AQU71788.1          YEIYQAAKNSTVCSNIYCLGVEPGYYFLNWVFS---PFASYSIFLMILAVLIIPIKTFFF
                       ::                   :  :                      :         

AAT85653.1          KHFENGSFVIVAIMCMFLWS-----VYVEAIRQALALSIVIFGIHSLFLGRKRKFITLVL
ABI98976.1          KVKNHPNFCLLFVFSIFGFM-----EFAEQIRQGVAISFILLAVDNLLVKKNKKFIFYVI
WP_046788607.1      KVKNHPNFCLLFVFSIFGFM-----EFAEQIRQGVAISFILLAVDNLLVKKNKKFIFYVI
WP_000456161.1      KVKNHPNFCLLFVFSIFGFM-----EFAEQIRQGVAISFILLAVDNLLVKKNKKFIFYVI
BAQ00746.1          YRETEKPTLVLFLFYSTSFLW----LDFILIRQSISVGFFILAISFFKNNKKIFACLFLI
AAM27879            WRLGVF--PLLAFFSCILVSFV---FLDNMLRQQVAFGFILVSVTCVRDRKILAFVCLC-
BAQ01563.1          KQIPKGVNKSLILFMLVAFIYP---LYNDAIRQLFAFCIILPLLPNIKSIAIKKIIITCG
ACA24852.1          KNTKNYLFCIGFFFLYQFI------FVTEAIRQIIALSIILVAYKKFYDGKKLQFHMLTI
ACA24840.1          KNTKNYLFCIGFFFLYQFI------FVTETIRQIIALSIILVAYKKFYDGKKLQFHMLTI
AHB32861.1          KKIENYWIPILVAFPYLILV-----VSMGYTRQSVAIAFVSFAILYGLERDIRKFYIFSF
AHB32215.1          IRLKKYWLCLLIYYPYHILA-----VSLGYTRQSIAVAILLYAFLKLIQNDRNKFLFFLL
AHB32799.1          VQLNKYWLCLLIYYPCHILT-----LSLGYTRQSIAVAIITYSFVKLFENKKISFIFYVI
BAQ01293.1          KRAY----VNYSLFMFIFIAASYLRLELSTIRQGLAVVIVIYSYSLLLNSKINLSLLFIF
AQU71788.1          YKMSDFPFLALLLYFCIML------YDVFPVRQSLATSLCLLYFLIYKEHKKLSIAILIA
                                                   ** .:  :                     

AAT85653.1          FASTFHITALICFLLMTPLFSKKLSKIISY--SLLIFSSFFFAFSETILSALLAIL-PEG
ABI98976.1          CAAMFHISAIVCLLFLYLVKLLDRKNKAFIMLSLIIWAVFLSLH---LMFNIYRFF-GVS
WP_046788607.1      CAAMFHISAIVCLLFLYLVKLLDRKNKAFIMLSLIILGSVSVIAFNVLINNID-FF-GVS
WP_000456161.1      CAAMFHISAIVCLLFLYLVKLLGRKNKAFIMLSLIILGGVSVIAFNVLINNID-FF-GVS
BAQ00746.1          LSSLFHETAIFAGVVFYILYRAEKAGFLFTIGSVLIIAPF--------LSDIITII-NDM
AAM27879            LASSFHFSAVFFIPFYFLYISFSFRNLFAF---VAVLSFFIGLSGNSIVDYLVNFLAGAD
BAQ01563.1          IAALFHSSIILMVPLFILMRRELTQKFMFYSFICALLFLSLLINIEFIVNTLNNLI-P--
ACA24852.1          LACSFHISAVIVFILIPFL----KRRNIYILKILTIVGLVLAIFSVYPVDYLIQLL----
ACA24840.1          LACSFHISAVIVFILIPFL----KRRNIYILKILTIVGLVLAIFSVYPVDYLIQLL----
AHB32861.1          LAILFHKSAIIVFMFLPLLLNLKYFN-------STLFFSFYSLFSFLTMSGLV----YYS
AHB32215.1          LAACFHKTAIIFILFYPLLFIKRKKI-------LIFLYEFFSLV---LITIVL----YVS
AHB32799.1          LASMFHRTAILLLIFYPLQLLMNRRN-------ISILYQFFSLF---LTTALL----YIS
BAQ01293.1          LAICFHRSAAIVLLFFPFVYYNSARNIHYF--IVILTIPFVILSGELNVVFIK----ILN
AQU71788.1          ALSI-HYTSIIFFVSLFIC---TREKILTIKNIILLILSYVTLTLIIM---------SPP
                         * :  .                        .                        

AAT85653.1          SIASEKLSFYLATEQYRPQLSIGSGTILDIILIF-LICVSFKRIKKYMLANYNAA-----
ABI98976.1          GFIATKLKGYAESDGSESG-ILSAGLLLNIMVIV----ICLLSIQGRHLK----------
WP_046788607.1      GFIATKLKGYAESDGSESG-ILSAGLLLNIMVIV----ICLLSIQGRHLK----------
WP_000456161.1      GFIATKLKGYAESDGSESG-ILSAGLLLNIMVIV----ICLLSIQGRHLK----------
BAQ00746.1          TIKNNNITLYLEQRT-----LPSIANVIELTIAF---VAFYIINKNSVFRESNEYKI---
AAM27879            GGYLGRALAYLEFDGY----PVTLGHYFRFLILL-MFVFLDLVIRGRQLSEQDSRI----
BAQ01563.1          KMLYVKLVNYVNNMG-----EFKVGFFAVIDFLG----ICIFCATYRVFKSNNDISV---
ACA24852.1          SLLPA--GGYIEKIRWYSQ-DDYAGSVLTFSLVFKVFVVLLFDYRFKSIKSHGQSLINAR
ACA24840.1          SLLPA--GGYIEKIRWYSQ-DDYAGSVLTFSLVFKVFVVLLFDYRFKSIKSHGQSLINAR
AHB32861.1          SLSGDNI--YTNQNSE----VSSAGAIFRVVVHF-LALFFYLLYRKKIVNSFNNYRI---
AHB32215.1          SLSENTV--YTSE--E----LNSSGVFLRLSLHI-IPVISYFLLRNKVFKIDKSYLI---
AHB32799.1          SLYDSNI--YTSDDSE----ISSSGVFMRIALHI-IPLVCYFSFRKKIFLNNNERQL---
BAQ01293.1          AFNSSLLNAYISKLIIYLS-LNKQAIINPQAMAL--LVFYFICIRVCDVKNKKQ------
AQU71788.1          EILASRINDYILNQKVYSEDITMTRNILKSIDQILIISICIGMLSKTDFS----------
                             *                                      .           

AAT85653.1          -NEILLIGCC--LYISFGIFIGKMMPVMTRIGWYGFPFVIVLLYINLGYSEYFKRYINKR
ABI98976.1          ---YYLSSVF--SFFVIQS---KIVSIAYRFSYYGYAFI---------YESFEWLYMANK
WP_046788607.1      ---YYLSSVF--SFFVIQS---KIVSIAYRFSYYGYAFI---------YESFEWLYMANK
WP_000456161.1      ---YYLSSVF--SFFVIQS---KIVSIAYRFSYYGYAFI---------YESFEWLYMANK
BAQ00746.1          -YKSILYSSL--CILLLSY----TIPSLARFLEFFRFFYFI-------LVVRMLMQFNVR
AAM27879            -WRLISSGVI--LMLFYEMVFYEFSVFWMRIREYFLVFFMVSPLFL--FRVFFWRE----
BAQ01563.1          ----YAIGTF--YFFILHL-VFYGAPFLQRLL-YYIFPLLSV------YSCFIFSHCQRG
ACA24852.1          AYDFIYTSVY--LMIFMDVYLGRFGTISTRLDVYFIPCFLIA------LNHLINEHKQGV
ACA24840.1          AYDFIYTSVY--LMIFMDVYLGRFGTISTRLDVYFIPCFLIA------LNHLINEHKQGV
AHB32861.1          -FDYMSLLII--FVFLLAI---PFSTLADRFNLYLIIFDIL-------VFSYLFSNISVN
AHB32215.1          -LDYFVLLIF--YCVGLSF---IFSTLADRFNLYLIFFDLY-------VVCMLYHNLKLV
AHB32799.1          -LDYFVMLII--YCLFLAF---IYSTLVDRFNFYLIFFDLF-------VIVSTYKYLNSK
BAQ01293.1          ---IIFLNII--ACQVIISFYFIFLTQLIIMRLVYY-FQVG-------WICWVIILYKEY
AQU71788.1          -RTILNLSIFGSIIFILGT---FLAPQLARFGLFFVPFQII-------SISSSLLLVQKH
                                                  :                             

AAT85653.1          --GCGYSKLLIAFYFLLQILRPLTYDYSYYN--IMHQDTL--LNRFDALDDA--SLRQSA
ABI98976.1          --GRLFNKLAMIIVLLVFAFKPLLN-PVYLD--MFNDYHFFWFGFLDTLPDV--NITQV-
WP_046788607.1      --GRLFNKLAMIIVLLVFAFKPLLN-PVYLD--MFNDYHFFWFGFLDTLPDV--NITQV-
WP_000456161.1      --GRLFNKLAMIIVLLVFAFKPLLN-PVYLD--MFNDYHFFWFGFLDTLPDV--NITQV-
BAQ00746.1          --SRYLFFVIILAYCFMRLNSFINQFDSGFD--YI--YNGKIL-----------------
AAM27879            --ARIFSALYVVYPLAVF-WGVITGLPVYDD--LYRDYRNYIV-YLAVGDDGFDSIRDLA
BAQ01563.1          SGARILLPLTLIMTLSVF-ARNIFNPYYATD--FYEPKFFYTDGVFEKHLDV--ERLKY-
ACA24852.1          --SRFIFFFVVMVYFTIN-YLSIMNGYYFEK--FYSPYQNYITEFLNPGSYS--DRGWD-
ACA24840.1          --SRFIFFFVVMVYFTIN-YLSIMNGYYFEK--FYSPYQNYITEFLNPGSYS--DRGWD-
AHB32861.1          --SRKIMVLTVIFFNSLMLYIW-LNFGAWSH--AWLPYQNYLLRYI--------------
AHB32215.1          --NRKIFIFILTIFLTSFIYIWMLNSVLVSK--AWLPYQNYLIDYL--------------
AHB32799.1          --SRLLFMSVLVIFYTIFILTWLLNSKFVLS--AWTPYQNYLIDYL--------------
BAQ01293.1          FRPKWLCFFLICL---LFITKSILNFRYEQDRAVFFPYYNVISSYLDDNYG---------
AQU71788.1          --SKFITFLIIVIYATIKLHL------------IILPFYDLFVPF---------------
                              :                                                 

AAT85653.1          KRKCFDLGKIGYGFLCSI
ABI98976.1          -KRCSTLLNHGIQY-CRR
WP_046788607.1      -KRCSTLLNHGIQY-CRR
WP_000456161.1      -KRCSTLLNHGIQY-CRR
BAQ00746.1          ------------------
AAM27879            AQDYWDRWRRGELR----
BAQ01563.1          -RKCSVIDEYDPNF-CPK
ACA24852.1          -VRYYFSNKELLQ-----
ACA24840.1          -VRYYFSNKELLQ-----
AHB32861.1          -LEYI-------------
AHB32215.1          -LNYVF------------
AHB32799.1          -LSYVF------------
BAQ01293.1          -RSRSFILNKADEL-FKE
AQU71788.1          -KIHI-------------
                                      
