CLUSTAL multiple sequence alignment by MUSCLE (3.8)


AFC91472.1      ---------MINLNPVA--ILTLLYLSINFLSMLIGCSSGEIQ---VETSIFRVSEESLI
AFC91514.1      ---------MINLNPVA--ILTLLYLSINFLSMLIGCSSGEIQ---VETSIFRVSEESLI
AAO39700.1      ---------MINLNPVA--ILTLLYLSINFLSMLIGCSSGEIQ---VETSIFRVSEESLI
AFC91570.1      ---------MINLNPVA--ILTLLYLSINFLSMLIGCSSGEIQ---VETSIFRVSEESLI
AAR97964.1      ---------MINLNPVA--ILTLLYLSINFLSMLIGCSSGEIQ---VETSIFRVSEESLI
AAD44158.1      ------MRKNFYTTP-----ITLLILTLNIAATIVVINNSELLIGDLMG--FKSETVVII
BAH24292.1      ------MRKNFYTTP-----ITLLILTLNIAATIVVINNSELLIGDLMG--FKSETVVII
BAQ00879.1      --------MFLFKKPKF--IFLLLFIISNIYSCLYFINTGHLL-GEVSDFNFKSEETSIY
ABG81806.1      MYLTTNYCDFLSRTRIVRRIFLLVYLISNVYAYIVFTETGVLI-GDYQGVLIIYKDQVVY
BAQ02068.1      MYLTTNYCDFLSRTRIVRRIFLLVYLISNVYAYIVFTETGVLI-GDYQGVLIIYKDQVVY
BAQ02224.1      MYLTTNYCDFLSRTRIVRRIFLLVYLISNVYAYIVFTETGVLI-GDYQGVLIIYKDQVVY
AJR19430.1      --------------------------------MLISC-----------------------
                                                 :                          

AFC91472.1      YSFLLQAICLIFLYYIYKYFTNRISYPPLTFKA----------KWGRALLIIQIAFIIFN
AFC91514.1      YSFLLQAICLIFLYYIYKYFTNRISYPPLTFKA----------KWGRALLIIQIAFIIFN
AAO39700.1      YSFLLQAICLIFLYYIYKYFTNRISYPPLTFKA----------KWGRALLIIQIAFIIFN
AFC91570.1      YSFLLQAICLIFLYYIYKYFTNRISYPPLTFKA----------KWGRALLIIQIAFIIFN
AAR97964.1      YSFLLQAICLIFLYYIYKYFTNRISYPPLTFKA----------KWGRALLIIQIAFIIFN
AAD44158.1      QSLIYISLSLLFLSVLYNGLE---KIKPLTTKLAD----SNSRPIAIFLICLELLYITYV
BAH24292.1      QSLIYISLSLLFLSVLYNGLE---KIKPLTTKLAD----SNSRPIAIFLICLELLYITYV
BAQ00879.1      INLLIIFFYLFFLVVIFRFFS-KIHVNSLLDNDCRIKWCKAEFFWGKLLIIIQILFIFYF
ABG81806.1      LLMLTIMSYYIVCGPVFNCLS-KVKIRLRTFKGLN--------SFAYILFFFQILFAVFN
BAQ02068.1      LLMLTIMSYYIVCGPVFNCLS-KVKIRLRTFKGLN--------SFAYILFFFQILFAVFN
BAQ02224.1      LLMLTIMSYYIVCGPVFNCLS-KVKIRLRTFKGLN--------SFAYILFFFQILFAVFN
AJR19430.1      -------------------------------------------------FFFQILFAVFN
                                                                 : ::: :  : 

AFC91472.1      TQMGVNTAGSVERIEGQSLSNYLFIILQPDILVAVISVCLNS---GFLFWTNILVYLLSM
AFC91514.1      TQMGVNTAGSVERIEGQSLSNYLFIILQPDILVAVISVCLNS---GFLFWTNILVYLLSM
AAO39700.1      TQMGVNTAGSVERIEGQSLSNYLFIILQPDILVAVISVCLNS---GFLFWTNILVYLLSM
AFC91570.1      TQMGVNTAGSVERIEGQSLSNYLFIILQPDILVAVISVCLNS---GFLFWTNILVYLLSM
AAR97964.1      TQMGVNTAGSVERIEGQSLSNYLFIILQPDILVAVISVCLNS---GFLFWTNILVYLLSM
AAD44158.1      FNTGLFVAGNNERGGG--VISALFVLLNVDVLVLIFLTHVKT---SKYKPIIIMLWIISF
BAH24292.1      FNTGLFVAGNNERGGG--VISALFVLLNVDVLVLIFLTHVKT---SKYKPIIIMLWIISF
BAQ00879.1      CLTNTFGANSVNRDGG--IISALWVVLSPDNLFFIYYSIFRK---SRYAKYNLLLAILSN
ABG81806.1      ISTGSNAAGTDFQTGG--VIRLLWLFLPVDYLFYIYYFVGREKKVSKIYLANVVIFILSM
BAQ02068.1      ISTGSNAAGTDFQTGG--VIRLLWLFLPVDYLFYIYYFVGREKKVSKIYLANVVIFILSM
BAQ02224.1      ISTGSNAAGTDFQTGG--VIRLLWLFLPVDYLFYIYYFVGREKKVSKIYLANVVIFILSM
AJR19430.1      ISTGSNAAGTDFQTGG--VIRLLWLFLPVDYLFYIYYFVGREKKVSKIYLANVVIFILSM
                   .   *..  .  *  :   *::.*  * *. :     .    .      ::: ::* 

AFC91472.1      FLRGWMGGTFVILFLILS--RYQNLRISLKTFLVSLCSLLLLFSILPALIEAKWAMRTGI
AFC91514.1      FLRGWMGGTFVILFLILS--RYQNLRISLKTFLVSLCSLLLLFSILPALIEAKWAMRTGI
AAO39700.1      FLRGWMGGTFVILFLILS--RYQNLRISLKTFLVSLCSLLLLFSILPALIEAKWAMRTGI
AFC91570.1      FLRGWMGGTFVILFLILS--RYQNLRISLKTFLVSLCSLLLLFSILPALIEAKWAMRTGI
AAR97964.1      FLRGWMGGTFVILFLILS--RYQNLRISLKTFLVSLCSLLLLFSILPALIEAKWAMRTGI
AAD44158.1      LQRGWISYFFILILISFIDRRLKNKKNWKA-GVVLIC--FIL--ALPFVEQIKNSIRSGE
BAH24292.1      LQRGWISYFFILILISFIDRRLKNKKNWKA-GVVLIC--FIL--ALPFVEQIKNSIRSGE
BAQ00879.1      ILRGWSGILIFIVFIELC-YRYREGKLKIR-LLSKICGIMFL--LYPVILAVKYGIRDSF
ABG81806.1      LSRGWLGWTLVLLYAELCFFFYSQKKIKIK-YLILL---FFLLIVAPLAFSLKIQLRADL
BAQ02068.1      LSRGWLGWTLVLLYAELCFFFYSQKKIKIK-YLILL---FFLLIVAPLAFSLKIQLRADL
BAQ02224.1      LSRGWLGWTLVLLYAELCFFFYSQKKIKIK-YLILL---FFLLIVAPLAFSLKIQLRADL
AJR19430.1      LSRGWLGWTLVLLYAELCFFFYSQKKIKIK-YLILL---FFLLIVAPLAFSLKIQLRADL
                : *** .  :.::   :      : .      :  :   ::*    *     *  :* . 

AFC91472.1      ------------SLSVFISNMSSYVTPENYYAGINYLLNRFQHVGHLALIYENADDLFKK
AFC91514.1      ------------SLSVFISNMSSYVTPENYYAGINYLLNRFQHVGHLALIYENADDLFKK
AAO39700.1      ------------SLSVFISNMSSYVTPENYYAGINYLLNRFQHVGHLALIYENADDLFKK
AFC91570.1      ------------SLSVFISNMSSYVTPENYYAGINYLLNRFQHVGHLALIYENADDLFKK
AAR97964.1      ------------SLSVFISNMSSYVTPENYYAGINYLLNRFQHVGHLALIYENADDIFKK
AAD44158.1      ---------------RISTQLTFFDYADSFNQQFMKVVGRVQTVSHVAFITDNINQLQNL
BAH24292.1      ---------------AISTQLTFFDYADSFNQQFMKVVGRVQTVSHVAFITDNINQLQNL
BAQ00879.1      LTNSNFWESFDRSWLYVFNNNGVLGYINGLLFGIEQFFSRIQLFSNAVVVYSLKHELANF
ABG81806.1      ---------YSSGIGGVISTLSNIDYIQSYNNFIAGFLSRIQQLSNIVFFYDHQQELYKF
BAQ02068.1      ---------YSSGIGGVISTLSNIDYIQSYNNFIAGFLSRIQQLSNIVFFYDHQQELYKF
BAQ02224.1      ---------YSSGIGGVISTLSNIDYIQSYNNFIAGFLSRIQQLSNIVFFYDHQQELYKF
AJR19430.1      ---------YSSGIGGVISTLSNIDYIQSYNNFIAGFLSRIQQLSNIVFFYDHQQELYKF
                                . .        :.    :  ...*.* ..: ... .   :: : 

AFC91472.1      YNAGYFSSYYMDGMPQYFLVKMYNLDM-YKLSFYLVQYFFD--ITEPTWNINTGVVGWLY
AFC91514.1      YNAGYFSSYYMDGIPQYLLVKMYNLDM-YKLSFYLVQYFFD--ITEPTWNINTGVVGWLY
AAO39700.1      YNAGYFSSYYMDGIPQYLLVKMYNLDM-YKLSFYLVQYFFD--ITEPTWNINTGVVGWLY
AFC91570.1      YNAGYFSSYYMDGIPQYLLVKMYNLDM-YKLSFYLVQYFFD--ITEPTWNINTGVVGWLY
AAR97964.1      YNAGYFSSYYMDGIPQYLLVKMYNLDM-YKLSFYLVQYFFD--ITEPTWNINTGVVGWLY
AAD44158.1      KNNGESTDFFEENFIYIIAKKLGSADDKINTPDLL-ARYISP-SLDSSWNVNPSLIGWIF
BAH24292.1      KNNGESTDFFEENFIYIIAKKLGSADDKINTPDLL-ARYISP-SLDSSWNVNPSLIGWIF
BAQ00879.1      VITNKVTSYWQEGIYGIIWNRIFDLPTSYNLGEVL-ANFIDPQSIIGSWNSNPTFLSWLF
ABG81806.1      VSSDIVSNYAWEGLPQQTVAKLLGLDPGVDMHIFLYSHYISS-TSEAVTTLQVGFISWLF
BAQ02068.1      VSSDIVSNYAWEGLPQQTVAKLLGLDPGVDMHIFLYSHYISS-TSEAVTTLQVGFISWLF
BAQ02224.1      VSSDIVSNYAWEGLPQQTVAKLLGLDPGVDMHIFLYSHYISS-TSEAVTTLQVGFISWLF
AJR19430.1      VSSDIVSNYAWEGLPQQTVAKLLGLDPGVDMHIFLYSHYISS-TSEAVTTLQVGFISWLF
                   .  :.:  :.:      .: .     .    *   ::.        . :  .:.*::

AFC91472.1      ILRYESILFAFYIMLLLLVPYYVVSRFAGKRM-LSVLACFSIIYLFHGWLGAYVNLAFYA
AFC91514.1      ILRYESILFAFYIMLLLLVPYYVVSRFAGKRM-LSVLACFSIIYLFHGWLGAYVNLAFYA
AAO39700.1      ILRYESILFAFYIMLLLLVPYYVVSRFAGKRM-LSVLACFSIIYLFHGWLGAYVNLAFYA
AFC91570.1      ILRYESILFAFYIMLLLLVPYYVVSRFAGKRM-LSVLACFSIIYLFHGWLGAYVNLAFYA
AAR97964.1      ILRYESILFAFYIMLLLLVPYYVVSRFAGKRM-LSVLACFSIIYLFHGWLGAYVNLAFYA
AAD44158.1      IQNDLYVLPIIWVVLLCFLFTMLSKIIANDLYAMNMRWLFWLVFLFPGW-----IFQFTA
BAH24292.1      IQNDLYVLPIIWVVLLCFLFTMLSKIIANDLYAMNMRWLFWLVFLFPGW-----IFQFTA
BAQ00879.1      IDPFQIGIYLLFTIALCFITMFLVKKITSSTLSLDMLWYMWLILIMPGWFASLILFLNTL
ABG81806.1      LGTLSSVFYPLFVFAIICISLFLSKKLGGEKL-CALTWIMIFLSIMCGWYNAYLVYMQAL
BAQ02068.1      LGTLSSVFYPLFVFAIICISLFLSKKLGGEKL-CALTWIMIFLSIMCGWYNAYLVYMQAL
BAQ02224.1      LGTLSSVFYPLFVFAIICISLFLSKKLGGEKL-CALTWIMIFLSIMCGWYNAYLVYMQAL
AJR19430.1      LGTLSSVFYPLFVFAIICISLFLSKKLGGEKL-CALTWIMIFLSIMCGWYNAYLVYMQAL
                :      :  :: . :  :   : . : ..     :   : :: :: **           

AFC91472.1      CIISLLANIRLYRTVYIPCEK--
AFC91514.1      CIISLLANIRLYRTVYIPCEK--
AAO39700.1      CIISLLANIRLYRTVYIPCEK--
AFC91570.1      CIISLLANIRLYRTVYIPCEK--
AAR97964.1      CIISLLANIRLYRTVYIPCEK--
AAD44158.1      VIFSAFSIYFIKVHT--------
BAH24292.1      VIFSLLVFILLKYTLRTKRVKPL
BAQ00879.1      IIFYVITFIKLNVTIER------
ABG81806.1      ITFYFIMGFLNLITLEKTKINHT
BAQ02068.1      ITFYFIMGFLNLITLEKTKINHT
BAQ02224.1      ITFYFIMGFLNLITLEKTKINHT
AJR19430.1      ITFYFIMGFLNLITLEKTKINHT
                  :  :                 
